config/routes.rb
Rails.application.routes.draw do

#créé les 7 chemins REST pour gossip
	resources :gossips , :shallow => true do 
  	resources :comments
	end

	#créé les 7 chemins REST
	resources :comments

#créé les 7 chemins REST pour user, sauf le destroy, pour l'entité User
	resources :users, except: [:destroy] 

#créé seulement la route show pour les villes
	resources :cities, only: [:show]



#créé 3 chemins pour sessions
	resources :sessions, only: [:new, :create, :destroy]

#page d'accueil statique
  get 'home', to: 'static_pages#home'

#rails avait généré automatiquement "get 'home/welcome'", on change l'adresse pour une route dynamique mais on renvoit tjrs à la méthode welcome
  get 'home/:name', to: 'home#welcome'

#après avoir créé le controller team, on écrit ici : get URL to: controllervisé#méthodevisée
	get 'team', to: 'static_pages#team'

	get 'contact', to: 'static_pages#contact'
 



# DEPUIS QU'ON A MIS RESOURCES, ON N'A PLUS BESOIN DE CES COMMANDES INDIVIDUELLES

#afficher un user (méthode qu'on retrouvera dans gossips)  
#get '/:user', to: 'gossips#user'

#afficher un potin  
#  get 'gossips/:id', to: 'gossips#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	has_many :users

end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :gossip

	has_many :likes

#Pour permettre le commentaire de commentaires on rajoute :
  belongs_to :commentable, polymorphic: true, optional: true


end

app/models/gossip.rb
class Gossip < ApplicationRecord

#Infos sur les attributes indépendants :

	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true

#Infos sur les liens avec les autres classes 

	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags

	has_many :comments, as: :commentable #on rajoute le as::commentable pour permettre le commentaire de commentaires
	has_many :likes

	belongs_to :user

end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag 

end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

#différencier sender et recipient /!\ il faut aussi ajouter des choses dans la classe user
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

#Infos sur les attributes indépendants :

	validates :email,
		uniqueness: true, #impossible que 2 utilisateurs rentrent le même email
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } #impose le format d'un email

#Infos sur les liens avec les autres classes 

	has_many :gossips
	has_many :comments
	belongs_to :city

#pour différencier le sender du recipient dans les privates messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	def index

	end



	def show
		
	#on selectionne le user qui correspond au nom envoyé en cliquant sur le lien dans gossip
		@city = City.find(params["id"])
	end



	def new
		@city = City.new	
	end



	def create


	end


	def edit
	 
	end



	def update
	  
	end





end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


#telles que doivent être toutes les def de la classe gossip, en mode REST
	def index
		# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
	end



	def show
		# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
	#on selectionne le gossip qui correspond à l'id rentré dans l'adresse (params{"id"})
		@gossip = Gossip.find(params["id"])
		@comment = Comment.new


	#test count = Comment.find_by(gossip_id: params["id"])
	end



	def new
	  # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
		@gossip = Gossip.new	
	end



	def create
	  # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
	  # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
	  # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
	
  #ici on réceptionne les data du formulaire, envoyées par la méthode new (cf dans views)
	  @gossip = Gossip.create(user_id: params[:user_id], title: params[:title], content: params[:content])
	  @gossip.user = User.find_by(id: session[:user_id])
	  if @gossip.save# essaie de sauvegarder en base @gossip
		    # si ça marche, il redirige vers la page d'index du site
	    flash[:notice] = "Potin bien créé !"
	    redirect_to gossips_path #gossips_path est l'adresse de l'index
	  else
	  	# sinon, il render la view new (qui est celle sur laquelle on est déjà)
	    render :new
	  end
	end


	def edit
	  # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
	#on veut juste retrouver le bon potin, comme dans show!	
		@gossip = Gossip.find(params["id"])

	end



	def update
	  # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
	  # pour info, le contenu de ce formulaire sera accessible dans le hash params
	  # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)

	  @gossip = Gossip.find(params[:id])
	  if @gossip.update(title:params[:title], content:params[:content])
	    redirect_to @gossip
	  else
	    render :edit
	  end
	end


	def destroy

    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:notice] = 'Bien supprimé modafuck'
    redirect_to gossips_path

	end


end



#ça ne devrait pas être là, mais en attendant, la fiche user est là :	
	#def user
	#on selectionne le user qui correspond au nom envoyé en cliquant sur le lien dans gossip
		#@user = User.find_by(first_name: params["user"])
  #end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def welcome

		puts "$" * 60
	  puts "Voici le message de l'URL :"
		puts params[:name]                                         

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index

	end



	def show
	#on selectionne le user qui correspond au nom envoyé en cliquant sur le lien dans gossip
		@user = User.find(params["id"])
	end



	def new
		@user = User.new	
	end



	def create
#ici on réceptionne les data du formulaire, envoyées par la méthode new (cf dans views)
	  @user = User.create(first_name: params[:first_name], last_name: params[:last_name], )
	  @user.user = User.find_by(id: session[:user_id])
	  if @user.save# essaie de sauvegarder en base @user
		    # si ça marche, il redirige vers la page d'index du site
	    flash[:notice] = "Utilisateur bien créé!"
	    redirect_to gossips_path #gossips_path est l'adresse de l'index
	  else
	  	# sinon, il render la view new (qui est celle sur laquelle on est déjà)
	    render :new
	  end

	end


	def edit
	 
	end



	def update
	  
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
	  if (user_id == session[:user_id]) #here
	    @current_user ||= User.find_by(id: user_id)
	  elsif (user_id == cookies.signed[:user_id]) #and here
	    user = User.find_by(id: user_id)
	    if user && user.authenticated?(:remember, cookies[:remember_token])
	      log_in user
	      @current_user = user
	    end
	  end
	end

	def logged_in?
    !current_user.nil?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1>Bienvenue sur la fiche Villes de <%= @city.name %>  <br/> </h1>

<p>

	<div class="card">
	  <img class="card-img-top" src="https://www.tierra-latina.com/wp-content/uploads/2019/01/Valparaiso_Chili_voyage_sur_mesure_Tierra_Latina_08-1.jpg" alt="Card image cap">
	  
	  <div class="card-body">
	    <h5 class="card-title text-center"> Nom de la ville : <%= @city.name%> </h5>
	    <p class="card-text text-center"> Code postal : <%= @city.zip_code %>  </p>
	  </div>




	<ul>
    <% User.where(city_id: params[:id]).each do |user| %>    
			<li>   
        
        <%= user.first_name %> 
          
          <ul> <% Gossip.where(user_id: user.id).each do |gossip| %>
        		<li>   
    					<%= gossip.title %>
        		</li>
    			<%end %> </ul>

      </li>
    <%end %>
  </ul>
	  
				  


		<div class="badge badge-pill badge-danger"> 
				<%= link_to 'Retour maison', gossips_path %> 
		</div>	


	</div>




</p>

app/views/gossips/edit.html.erb
<html>
  <body>

<%= form_tag url_for(action: 'update'), method: "patch" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Content' %>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />

  <%= select_tag "tags", options_from_collection_for_select(Tag.all, "id", "title", multiple: true) %>
  <br /> <br />


  <%= submit_tag 'Update Post' %>

<% end %>
    <!-- ... -->
  </body>

</html>

app/views/gossips/index.html.erb
<html>
	<body>

<!-- Informe qu'on est bien connecté -->

		<% flash.each do |key, value| %>
 		<%= content_tag(:div, class: "alert alert-#{key} alert-dismissable") do %>
		<!-- affiche la notif   -->	
  	<%= value %>
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<!-- Souhaite la bienvenue à la personne connectée -->
		
		<% if session[:user_id] != nil %>
		<h2 class = text-center>Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h2>   
		<% end %>
 		<% end %> 
		<% end %>


			<div class = "jumbotron jumbotron fluid">
				<div class =  "container">
					<h1 class="my-4"> Voici le super site des potins de THP <br/></h1>
				</div>
				<div class="card-body text-center">
					<a class="btn btn-outline-warning" <%= link_to "Enregistrer un potin", new_gossip_path %> </div> <br/> </a>
				</div>
			</div>


<div class="container">



<h3><br/> Voir tous les potins </h3>
 
	<div class="card-columns">

		<% Gossip.all.each_with_index do |gossip| %>
		  <div class="card text-white bg-dark mb-3">
		    <div class="card-body">
		      <h5 class="card-title"> <%= gossip.title %> </h5>

		      <p class="card-text"> écrit par <%= gossip.user.first_name %> </p>
		    </div>

		    <div class="card-footer">
		      <small class="text-muted"> 

		      	<%= Comment.where(gossip_id: gossip.id).count || 0 %> commentaire(s) <br/>

		      	<button class="btn btn-warning"><%= link_to 'Voir ce potin',gossip_path(gossip.id) %> </button> </small>
		    </div>
		  </div>

		<% end %>

	</div>

</div>

</body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p> Try again motherfucker <br/>
        Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>



    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title' %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content' %>
      <br /> <br />
.
      <%= select_tag "tags", options_from_collection_for_select(Tag.all, "id", "title", multiple: true) %>
      <br /> <br />


      <%= submit_tag "Créer le gossip" %>

    <% end %>

  </body>

</html>

app/views/gossips/show.html.erb
<% flash.each do |key, value| %>
 		<%= content_tag(:div, class: "alert alert-#{key} alert-dismissable") do %>
		<!-- affiche la notif   -->	
  	<%= value %>
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<% end %>
		<% end %>


<h2><br/> Bonsoooir et bienvenue sur le gossip numéro <%= params["id"] %>  <br/> </h2>

<p>

<div class = "container d-flex justify-content-center"">

	<div class="card" style="width: 18rem;">

<!-- Affichage du gossip -->		
	  <div class="card-body bg-warning">
	    <h3 class="card-title text-center "> <br/><%= @gossip.title %> </h3>
	    <p class="card-text"> <br/> <br/> <%= @gossip.content %> </p>
	  </div>
	  
	  <ul class="list-group list-group-flush">

	    <li class="list-group-item text-right">écrit par <%= @gossip.user.first_name %></li>
	 		<li class="list-group-item text-right">à : <%= @gossip.user.city.name %></li>
	  	<li class="card-footer list-group-item"> <small class="text-muted">créé le : <%= @gossip.created_at%></small></li>
	  </ul>
	</div>

</div>

<div class = "container">
<!-- Formulaire pour écrire des comments -->

	<div class = "container ">
			<div style="font-family: 'Reenie Beanie', cursive;color: white; margin-top: 5%;font-size: 2em;" >
				<%= form_for :comment, :url=> {:controller => 'comments', :action => 'create'} do |f| %>
				<%= f.text_area :content %>
				<%= f.hidden_field :id , :value => @gossip.id %>
				<%= f.submit %>
				<% end %>
			</div>
	</div>

<!-- Affichage des commentaires -->
	  <ul>
    	<% Comment.where(gossip_id: @gossip.id).reverse.each do |comment| %>
      
      	<p> <%= comment.user.first_name %> a écrit : <br/>
        		<%= comment.content %> <br/>

       		<div class="card-footer"> 
       			<small class="text-muted">
		    
			  			<a class="badge badge-pill badge-light"<%= link_to "Editer ce comment",edit_comment_path(comment) %> </button> </a><br/>
							<a class="badge badge-pill badge-danger" <%= link_to 'Supprimer ce commentaire', comment_path(comment), method: 'delete' %> </a><br/>
					</div> 
					</small>
      	</p>
         
    	<%end %> 
  	</ul>
</div>


<div class = "container fluid d-flex justify-content-around flex-wrap">
<!-- Boutons de sortie/redirection -->


	  	<a class="btn btn-warning" <%= link_to "Editer ce gossip",edit_gossip_path(@gossip.id) %> 
			<br/>  </a> 

			<a class="btn btn-warning"<%= link_to 'Fiche auteur',user_path(@gossip.user.id) %> <br/> </a> 
	  	<a class="btn btn-warning" <%= link_to "Voir la fiche ville de l'auteur",city_path(@gossip.user.city_id) %> <br/></a>

			<a class="btn btn-warning" <%= link_to 'Supprimer ce gossip', gossip_path(@gossip), method: 'delete' %> <br/></a> </div>

<div class= "d-flex justify-content-center" ">
			<a class=" btn btn-danger "	<%= link_to 'Retour maison', gossips_path %> <br/> </a> 
</div>
</p>

app/views/users/new.html.erb
<div style="margin: 5%;" >
    <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div style="font-family: 'Reenie Beanie';font-size: 3em;color: white;" >
      <%= label_tag 'Nom' %><br />
      <%= text_field_tag 'first_name'%>
      <br /> 
      <%= label_tag 'Prénom' %><br />
      <%= text_field_tag 'last_name'%>
      <br /> 
        <%= label_tag 'Age' %><br />
      <%= text_field_tag 'age'%>
      <br /> 
        <%= label_tag 'email' %><br />
      <%= text_field_tag 'email'%>
      <br /> 
        <%= label_tag 'password' %><br />
      <%= text_field_tag 'password'%>
      <br /> <br /> 
      <%= submit_tag "S'inscrire" %>

    <% end %>
  </div>
</div>    

app/views/users/show.html.erb
<h1>Bienvenue sur la fiche utilisateur de <%= @user.first_name + " " + @user.last_name %>  <br/> </h1>

<p>

<div class="card">
	<img class="card-img-top" src="https://i.kym-cdn.com/entries/icons/facebook/000/016/546/hidethepainharold.jpg" alt="Card image cap">
	  
	<div class="card-body">

	  <h5 class="card-title text-center"><%= @user.first_name + " " + @user.last_name%></h5>
	  <p class="card-text"> <br/> <br/> Se définit comme : <%= @user.description %>  </p>

	</div>
	  
	<ul class="list-group list-group-flush">

		<li class="list-group-item "> Age : <%= @user.age %> ans <br/></li>
		<li class="list-group-item "> Email : <%= @user.email%> <br/></li>
	  <li class="list-group-item "> Ville : <%= @user.city.name%>  <br/></li>

	</ul>

	<div class="card-body text-center">

		<div class="badge badge-pill badge-danger"> 
	  		<%= link_to 'Voir la fiche ville associée',city_path(@user.city_id) %>
		</div>

		<div class="badge badge-pill badge-danger"> 
				<%= link_to 'Retour maison', gossips_path %> 
		</div>	
	</div>
</div>

</p>