config/routes.rb
Rails.application.routes.draw do

#créé les 7 chemins REST pour gossip
	resources :gossips , :shallow => true do 
  	resources :comments
	end

	#créé les 7 chemins REST
	resources :comments

#créé les 7 chemins REST pour user, sauf le destroy, pour l'entité User
	resources :users, except: [:destroy] 

#créé seulement la route show pour les villes
	resources :cities, only: [:show]



#créé 3 chemins pour sessions
	resources :sessions, only: [:new, :create, :destroy]

#page d'accueil statique
  get 'home', to: 'static_pages#home'

#rails avait généré automatiquement "get 'home/welcome'", on change l'adresse pour une route dynamique mais on renvoit tjrs à la méthode welcome
  get 'home/:name', to: 'home#welcome'

#après avoir créé le controller team, on écrit ici : get URL to: controllervisé#méthodevisée
	get 'team', to: 'static_pages#team'

	get 'contact', to: 'static_pages#contact'
 



# DEPUIS QU'ON A MIS RESOURCES, ON N'A PLUS BESOIN DE CES COMMANDES INDIVIDUELLES

#afficher un user (méthode qu'on retrouvera dans gossips)  
#get '/:user', to: 'gossips#user'

#afficher un potin  
#  get 'gossips/:id', to: 'gossips#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	has_many :users

end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :gossip

	has_many :likes

#Pour permettre le commentaire de commentaires on rajoute :
  belongs_to :commentable, polymorphic: true, optional: true


end

app/models/gossip.rb
class Gossip < ApplicationRecord

#Infos sur les attributes indépendants :

	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true

#Infos sur les liens avec les autres classes 

	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags

	has_many :comments, as: :commentable #on rajoute le as::commentable pour permettre le commentaire de commentaires
	has_many :likes

	belongs_to :user

end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag 

end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

#différencier sender et recipient /!\ il faut aussi ajouter des choses dans la classe user
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

#Infos sur les attributes indépendants :

	validates :email,
		uniqueness: true, #impossible que 2 utilisateurs rentrent le même email
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } #impose le format d'un email

#Infos sur les liens avec les autres classes 

	has_many :gossips
	has_many :comments
	belongs_to :city

#pour différencier le sender du recipient dans les privates messages
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def welcome

		puts "$" * 60
	  puts "Voici le message de l'URL :"
		puts params[:name]                                         

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
	  if (user_id == session[:user_id]) #here
	    @current_user ||= User.find_by(id: user_id)
	  elsif (user_id == cookies.signed[:user_id]) #and here
	    user = User.find_by(id: user_id)
	    if user && user.authenticated?(:remember, cookies[:remember_token])
	      log_in user
	      @current_user = user
	    end
	  end
	end

	def logged_in?
    !current_user.nil?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


<!-- Liens pour bootstrap -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<!-- Barre de navigation -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/gossips">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>

    </ul>
  </div> 

  
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="cette barre ne sert à R" aria-label="Search">
    </form>


  <% if session["user_id"] != nil %>

    <a class= "btn btn-outline-success my-2 my-sm-0" <%= link_to "Se déconnecter", session_path(session.id), method: :delete %> </a>


  <% else %>

    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Qui es-tu?
      </button>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <button class="dropdown-item"> <%= link_to "Se connecter", new_session_path %> </button>
        <button class="dropdown-item"> <%=link_to "S'inscrire", new_user_path %> </button>
      </div>
      </div>


  <% end %>



  </nav>



  </head>

  <body>
    <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
    <%= yield %> 
  </body>
</html>